project:
  type: website
  output-dir: docs

website:
  title: "Xiao Yu - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Weekly Notes"
        menu: 
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1 Notes"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2 Notes"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3 Notes"
          - href: weekly-notes/week-04-notes.qmd
            text: "Week 4 Notes"
          - href: weekly-notes/week-05-notes.qmd
            text: "Week 5 Notes"
          - href: weekly-notes/week-06-notes.qmd
            text: "Week 6 Notes"

      - text: "Labs"
        menu:
          - href: labs/lab0/script/lab0_template.qmd
            text: "Lab 0: dplyr Basics"
          - href: labs/lab1/week-03/script/week3_lab_exercise.qmd
            text: "Lab 1: Data Visualization and EDA"
            
      - text: "Assignments"
        menu:
          - href: Assignments/Assignment_1/Assignment_1.qmd
            text: "Assignment 1: Census Data Exploration"
          - href: Assignments/Assignment_2/Yu_Xiao_Assignment2.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"
          - href: Assignments/Midterm/Yu_Xiao_Appendix.qmd
            text: "Midterm: Philadelphia Housing"
          - href: Assignments/Midterm/final_slides.qmd
            text: "Midterm Slides"
          - href: Assignments/Assignment_4/Yu_Xiao_Assignment4.qmd
            text: "Assignment 4: Spatial Predictive Analysis of Burglaries in Chicago"
          - href: Assignments/Assignment_5/Yu_Zheng_Assignment5.qmd
            text: "Assignment 5: Space-Time Prediction of Bike Share Demand: Philadelphia Indego"
          - href: Assignments/Final/1.qmd
            text: "Final Challenge"
          - href: Assignments/Final/fslides.qmd
            text: "Final Slides"
            
            
   
            
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
